services:
  superset:
    build: .
    image: apache-superset-custom
    container_name: superset-1
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_DATABASE_URI=sqlite:////app/superset.db
      - SECRET_KEY=Hf1UPnkcSuJBvesM660puz56yhiSEVvrOWgMLFG16ER+4Iyz5MFIjcRF
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command: >
      bash -e -c "
      superset db upgrade &&
      superset init &&
      superset load_examples &&  # Thêm lệnh để tải dữ liệu mẫu
      /app/init_user.sh &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  superset_home:
