services:
  superset:
    build: .
    image: apache-superset-custom
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_DATABASE_URI=sqlite:////app/superset.db
      - SUPERSET_SECRET_KEY=Hf1UPnkcSuJBvesM660puz56yhiSEVvrOWgMLFG16ER+4Iyz5MFIjcRF  # Nên thay đổi key của bạn
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/superset_config.py  # Sao chép file config
    command: >
      bash -c "
      superset db upgrade &&
      superset init &&
      /app/init_user.sh &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  superset_home:
